version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: base_php-fpm
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/config/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php-fpm/logger/php-fpm.log:/var/log/php-fpm.log
    networks:
      - base_laravel
  nginx:
    image: nginx:latest
    container_name: base_nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/logger:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT}:80"
    networks:
      - base_laravel
  redis:
    image: "redis:latest"
    container_name: "base_redis"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
     - "${REDIS_PORT}:6379"
    volumes:
     - ./docker/redis:/data
    networks:
     - base_laravel
    expose:
     - "${REDIS_PORT}"
  mysql:
    image: mysql:8.0
    container_name: base_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./docker/mysql/database:/var/lib/mysql
    networks:
      - base_laravel
networks:
  base_laravel:
volumes:
  mysql_data:
    driver: local
